### ISSUE TITLE
Question about a test check_mode.yml for vm_params

### ISSUE THREAD

**Issue by kbothwell** [ScaleComputing/HyperCoreAnsibleCollection#275]
## Describe the bug
Not a bug but a question. This [test](https://github.com/ScaleComputing/HyperCoreAnsibleCollection/blob/main/tests/integration/targets/i_vm_params/tasks/check_mode.yml) appears to be checking whether or not  `check_mode` is functioning for the the `vm_params` module, [but that module does not support `check_mode`](https://github.com/ScaleComputing/HyperCoreAnsibleCollection/blob/main/plugins/modules/vm_params.py#L77). Will check_mode be supported for this module in the future?

**Comment by justinc1** [comment]
Check mode will likely not be implemented. Initially (before first release) the `vm_params` module did have check mode, and that's why this test file is still there.

In check mode the module needs to realistically simulate what would happen. Ideally the returned output is usable in next ansible task. If task using `vm_params` will power on a VM, then in check mode the returned value will be like `before power_state=off, after power state=on`. That does work.

But if `vm` module needs to add a disk to VM, what disk UUID should be returned? Any later task using the returned UUID will notice there is no such disk.

**Comment by kbothwell** [comment]
Yes, my apologies.
