### ISSUE TITLE
:rocket: Cloud Init without requirment for „yes“ confirmation

### ISSUE THREAD

**Issue by christianhahnsft22** [ScaleComputing/HyperCoreAnsibleCollection#341]
when creating a vm and using cloud init to automate my ubuntu installation I need to confirm it with yes. 

can this be also automated to have a fully automated setup ?

**Comment by justinc1** [comment]
The text on screen is `Continue with autoinstall? (yes|no)`, right? Problem was we need to modify kernel commandline before kernel is booted in order to skip this question. Normally we would build custom ISO image (e.g. remaster original ISO image) - but than you need to remember official ubuntu image is not 'good enough'.

Looking at https://askubuntu.com/questions/1513521/autoinstall-in-cloud-init-stops-with-question-continue-with-autoinstall-yesn, it is enough to fake this - answer in link hides real /proc/cmdline, so that subiquity thinks ISO was booted with the `autoinstall` param. Can you give it a try?

**Comment by ddemlow** [comment]
thats a good find if it works ^ ... fingers crossed

and of course - using a ready to run ubuntu cloud image is another option as it's already armed to run cloud-init.  there is an examples of the url2template role that uses a cloud image to create a vm template here https://github.com/ScaleComputing/HyperCoreAnsibleCollection/blob/main/examples/url2template/url2template.yml

and then the template2vm role that takes a template and clones it to a VM supplying cloud-init and other vm customizations https://github.com/ScaleComputing/HyperCoreAnsibleCollection/blob/main/examples/url2template/template2vm.yml

**Comment by christianhahnsft22** [comment]
thx the askubuntu thread was the right solution for overcoming the issue :)
