### ISSUE TITLE
CI tests on github missed one bug

### ISSUE THREAD

**Issue by justinc1** [ScaleComputing/HyperCoreAnsibleCollection#42]
PR https://github.com/ScaleComputing/HyperCoreAnsibleCollection/pull/40 at commit 99f438f7a241c5e7310d980a0b709e0bee038984 - CI tests passed, see https://github.com/ScaleComputing/HyperCoreAnsibleCollection/actions/runs/3248895324/jobs/5330654368.

Same CI tests on gitlab.xlab.si failed - https://gitlab.xlab.si/scale-ansible-collection/HyperCoreAnsibleCollection/-/pipelines/37700 and https://gitlab.xlab.si/scale-ansible-collection/HyperCoreAnsibleCollection/-/jobs/89096

Why? What is wrong with github CI setup?
Possible cause - In log is "WARNING: Unable to determine context for the following test targets, they will be run on the target host: inventory, vm_git_issues"

Also, maybe we are interacting with different HC3 version?

**Comment by domendobnikar** [comment]
![Screenshot from 2022-12-12 11-09-34](https://user-images.githubusercontent.com/113340617/207019048-2738dd2b-874b-406b-b0e4-d56d63bfef1c.png)

There was keyError ' ' exception. There seemed to be an instance of a VM without defined machine type in Gitlab tests.
But Github tests didn't have a VM like that.
It had to be an API issue for this to happen, since a VM without defined machine type shouldn't be possible to create.
I tried creating a VM without machineType parameter with rawAPI and with webUI. It is always set to default: "scale-7.2"

Maybe a `keyError exception catch{}` should be implemented here? @justinc1 
Could be something like: "Machine type 'blabla' is not a valid type"
In the future there could be more `machineTypes`, at the very least we could have a better error popup to give us more information.

**Comment by ddemlow** [comment]
I know there have been support cases where VMs existed without machine types, likely from older version where there may have been some path to create them.  on current versions  they are not startable which usually is what triggers the support call
